DATABASE_USERNAME: sa
DATABASE_PASSWORD: password

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      max-lifetime: 1000000
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 10000
      maximum-pool-size: 100
  jpa:
    hibernate.ddl-auto: create
#    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    properties.hibernate.enable_lazy_load_no_trans: true
    generate-ddl: true
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
